services:
  frontend:
    build: frontend
    restart: always
    ports:
      - 8888:8080
    networks:
      - global

  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/farit/PycharmProjects/sound2art-clip/results:/app/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ "gpu" ]
    networks:
      - global


volumes:
  results:


networks:
  global:
    external: true