services:
  frontend:
    build: frontend
    restart: always
    ports:
      - 80:8080

  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/artcode/PycharmProjects/neuralsynthesia/results:/app/results
      - /home/artcode/PycharmProjects/neuralsynthesia/feed_forward_vqgan_clip:/app/feed_forward_vqgan_clip
      - /home/artcode/PycharmProjects/neuralsynthesia/rugpt3small_based_on_gpt2:/app/rugpt3small_based_on_gpt2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ "gpu" ]


volumes:
  results:
