version: '3.8'

services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "8888:8080"
    networks:
      - neuralsynthesia
    depends_on:
      - backend

  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
      - NEBIUS_BASE_URL=${NEBIUS_BASE_URL:-https://api.studio.nebius.ai/v1}
      - OAUTH=${OAUTH}
      - FOLDER_ID=${FOLDER_ID}
    env_file:
      - .env
    networks:
      - neuralsynthesia

volumes:
  results:

networks:
  neuralsynthesia:
    driver: bridge